format = "$all"
add_newline = true

[character]
success_symbol = "[▸>](bold green)"
error_symbol = "[▸>](bold red)"
vicmd_symbol = "[<◂](bold blue)"

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false
show_always = true

[directory]
style =	"bold white"

[cmd_duration]
style =	"white bold"
