#!/usr/bin/env bash

#
# [ BSPWM ]
#

# monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# border
#bspc config border_width 2
#bspc config focused_border_color \#b0af6f
#bspc config normal_border_color \#161b1b
bspc config border_width 5
bspc config focused_border_color \#A0CDEF
bspc config normal_border_color \#B3BCC7

# preselect (Use focused_border_color)
PRESELECT="$(bspc config focused_border_color)"
bspc config presel_feedback_color $PRESELECT

# window
bspc config window_gap 16
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# padding
bspc config top_padding 45
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

# rule
bspc rule -a feh state=floating

#
# [ X11 ]
#

# keyboard
setxkbmap us

# cursor
xsetroot -cursor_name left_ptr

#
# [ AUTOSTART ]
#

#screenlayout
~/.screenlayout/screen.sh &

# polkit
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# hotkey
sxhkd &

# panel
#tint2 &
~/.config/polybar/launch.sh & 

nm-applet &
fcitx &
blueman-applet &

# compositor
picom &

# wallpaper
nitrogen --restore &

# notification
dunst &

